### ISSUE TITLE
[CONFUSED] -fopenmp -O3" failed with exit status 1 ??

### ISSUE THREAD

**Issue by kroscek** [arogozhnikov/infiniteboost#7]
Hi. I don't understand why using pip install . throws me error:

Running setup.py install for infiniteboost ... error
    Complete output from command /home/lemma/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-Q3sQ_y-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RqOC6j-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "infiniteboost.fortranfunctions" sources
    f2py options: []
      adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
      adding 'build/src.linux-x86_64-2.7' to include_dirs.
      adding 'build/src.linux-x86_64-2.7/infiniteboost/fortranfunctions-f2pywrappers2.f90' to sources.
    build_src: building npy-pkg config files
    running build_py
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/infiniteboost
    copying infiniteboost/researchlosses.py -> build/lib.linux-x86_64-2.7/infiniteboost
    copying infiniteboost/researchboosting.py -> build/lib.linux-x86_64-2.7/infiniteboost
    copying infiniteboost/__init__.py -> build/lib.linux-x86_64-2.7/infiniteboost
    copying infiniteboost/researchtree.py -> build/lib.linux-x86_64-2.7/infiniteboost
    running build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    customize Gnu95FCompiler
    Found executable /usr/bin/gfortran
    customize Gnu95FCompiler
    customize Gnu95FCompiler using build_ext
    building 'infiniteboost.fortranfunctions' extension
    compiling C sources
    C compiler: gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fopenmp -O2 -march=core2 -ftree-vectorize -fPIC
    
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/infiniteboost
    compile options: '-Ibuild/src.linux-x86_64-2.7 -I/home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/home/lemma/miniconda2/include/python2.7 -c'
    gcc: build/src.linux-x86_64-2.7/fortranobject.c
    In file included from /home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                     from /home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from build/src.linux-x86_64-2.7/fortranobject.h:13,
                     from build/src.linux-x86_64-2.7/fortranobject.c:2:
    /home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    gcc: build/src.linux-x86_64-2.7/infiniteboost/fortranfunctionsmodule.c
    In file included from /home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                     from /home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from build/src.linux-x86_64-2.7/fortranobject.h:13,
                     from build/src.linux-x86_64-2.7/infiniteboost/fortranfunctionsmodule.c:19:
    /home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    build/src.linux-x86_64-2.7/infiniteboost/fortranfunctionsmodule.c: In function ‘initfortranfunctions’:
    build/src.linux-x86_64-2.7/infiniteboost/fortranfunctionsmodule.c:778:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       Py_TYPE(&PyFortran_Type) = &PyType_Type;
       ^
    compiling Fortran 90 module sources
    creating build/temp.linux-x86_64-2.7/infiniteboost
    Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
    Fortran f90 compiler: /usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
    Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
    compile options: '-Ibuild/src.linux-x86_64-2.7 -I/home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/home/lemma/miniconda2/include/python2.7 -c'
    extra options: '-Jbuild/temp.linux-x86_64-2.7/infiniteboost -Ibuild/temp.linux-x86_64-2.7/infiniteboost'
    extra f90 options: '-fopenmp -O3'
    gfortran:f90: infiniteboost/fortranfunctions.f90
    infiniteboost/fortranfunctions.f90:124.14:
    
            !$OMP SIMD
                  1
    Error: Unclassifiable OpenMP directive at (1)
    infiniteboost/fortranfunctions.f90:124.14:
    
            !$OMP SIMD
                  1
    Error: Unclassifiable OpenMP directive at (1)
    error: Command "/usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops -Ibuild/src.linux-x86_64-2.7 -I/home/lemma/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/home/lemma/miniconda2/include/python2.7 -c -c infiniteboost/fortranfunctions.f90 -o build/temp.linux-x86_64-2.7/infiniteboost/fortranfunctions.o -Jbuild/temp.linux-x86_64-2.7/infiniteboost -Ibuild/temp.linux-x86_64-2.7/infiniteboost -fopenmp -O3" failed with exit status 1
    
    ----------------------------------------
Command "/home/lemma/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-Q3sQ_y-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RqOC6j-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-Q3sQ_y-build/

....Even though I have GNU (gcc, g++, gfortran) installed in my machine. I have Intel i5 4 cores.

**Comment by arogozhnikov** [comment]
Hi, 
most probably, you have gcc 4.x or earlier, which doesn't have support for OMP SIMD.

You can resolve this by deleting this line in your copy/fork:
https://github.com/arogozhnikov/infiniteboost/blob/master/infiniteboost/fortranfunctions.f90#L124

**Comment by kroscek** [comment]
Thanks. Works like a charm!
